config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  root 'shangri_la#index'
  get 'shangri_la/index'

  get 'shangri_la/login_form'
  post 'shangri_la/login'
  get 'shangri_la/logout'
  post 'shangri_la/search'
  get 'shangri_la/info'
  get 'shangri_la/info_page'
  get 'shangri_la/likes'
 
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    validates :password, presence: true, confirmation: true
    
    attr_accessor :password, :password_confirmation
    
    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    # private
        def current_user
            if session[:login_uid]
            User.find_by(email: session[:login_uid])
            end
        end
end

app/controllers/graphql_controller.rb
# frozen_string_literal: true

class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = SSRSSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?
    handle_error_in_development(e)
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

app/controllers/shangri_la_controller.rb
class ShangriLaController < ApplicationController
   require 'httpclient'
  
  def index
    @users = User.all
  end
  
  def login
    
    user = User.find_by(email: params[:email])
    
    if user
      
      if BCrypt::Password.new(user.pass) == params[:pass]
        session[:login_uid]=params[:email]
        #session[:user_id] = user.id
        redirect_to root_path
      else
        flash[:alert] = '※パスワードが間違ってるヨ！'
        redirect_to shangri_la_login_form_path
      end
    else
      flash[:alert] = '※メールアドレスが間違ってるヨ！'
      redirect_to shangri_la_login_form_path
    end
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
  
  def search
    
    # APIのURLと必要なパラメータを設定
    url = URI.parse("https://anime-api.deno.dev/anime/v1/master/#{params[:anime_year]}/#{params[:anime_cool]}")
    
    # URLにパラメータを追加
    
    # APIにリクエストを送信
    response = Net::HTTP.get_response(url)
    
    # レスポンスをJSONとしてパース
    all_results = JSON.parse(response.body)
    #@result = JSON.parse(response.body)

    # キーワードに合致するもののみを抽出
    if params[:keyword] == ""
      @result = all_results
    else
      @result = all_results.select { |item| params[:keyword].present? && item['title'].include?(params[:keyword]) }
    end
    
    # レスポンスを表示
    render :index
  end
  
  def info
    item_json = params[:item]
    puts 'infoアクションに接続'
    @info = JSON.parse(item_json)
    render :info_page
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @users = User.all
  end
  
  def create
    if User.exists?(email: params[:email])
      flash[:alert] = '※そのメールアドレスは登録されてるで'
      redirect_to new_user_path
    else
      #hashed_password = BCrypt::Password.create(params[:pass])
      user = User.new(email: params[:email], password: params[:password], password_confirmation: params[:password_confirmation])
      if user.save
        redirect_to root_path
      else
        render 'new'
      end
    end
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shangri_la_helper.rb
module ShangriLaHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SSRS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
    <% end %>
  </body>
</html>

app/views/shangri_la/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>アニメ情報サイト</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        .search {
            min-width: 100%;
        }

        /* 中央配置 */
        .centered {
            display: flex;
            justify-content: center;
            align-items: center;
            max-width: 90ch; /* コンテンツ全体の横幅を90chに制限 */
            margin: 0 auto; /* ページ中央に配置 */
            background-color:#D2ECF9;
            font-family:-apple-system, "system-ui", "Hiragino Kaku Gothic ProN", "Hiragino Sans", Meiryo, sans-serif, "Segoe UI Emoji";
        }

        /* 検索エリアの幅を広げる */
        .wider {
            width: 400px; /* 検索フォームの幅を400pxに設定 */
        }
    </style>
</head>

<body class="p-5 pb-2.5">
    
    <div>
        <!--ナビゲーションバー-->
        <!-- ここにナビゲーションバーのコード -->
        
        <nav class="navbar navbar-expand bg-body-tertiary">
              <div class="container-fluid ">
                  <a class="navbar-brand" href="#">SSRS</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarNav">
                      <ul class="navbar-nav">
                          <li class="nav-item">
                            <% if current_user %>  <!-- ログイン中の場合 -->
                              <a class="nav-link active" aria-current="page" href="shangri_la/logout">サインアウト</a>  
                            <% else %> <!-- ログインしていない場合 -->
                              <a class="nav-link active" aria-current="page" href="shangri_la/login_form">サインイン</a>
                            <% end %>
                          </li>
                          <a class="nav-link active" aria-current="page" href="shangri_la/likes">お気に入り</a>
                      </ul>
                  </div>
              </div>
          </nav>
                
        <div class="centered mt-3">
            <!--検索フォーム-->

                <div class="border-solid border-2 border-sky-500">
                    
                    <%= form_tag({ action: :search }, method: :post, data: { turbo: false }) do %>

                    <!-- フィルター部分 -->
                        <div class="my-5">
                            <label class="sr-only" for="inlineFormInputName">キーワード検索</label>
                            <input type="text" class="form-control wider" id="inlineFormInputName" placeholder="青春ブタ野郎はバニーガール先輩の夢を見ない" name="keyword">
                        </div>

                        <label class="my-1 mr-2" for="inlineFormCustomSelectPref">放送年度</label>
                        <!-- 放送年度の選択肢 -->
                        <select class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref" name="anime_year">
                            <option selected>指定なし</option>
                            <option value="2015">2015</option>
                            <option value="2016">2016</option>
                            <option value="2017">2017</option>
                            <option value="2018">2018</option>
                            <option value="2019">2019</option>
                            <option value="2020">2020</option>
                            <option value="2021">2021</option>
                            <option value="2022">2022</option>
                            <option value="2023">2023</option>
                        </select><br>
  
                        <label class="my-1 mr-2" for="inlineFormCustomSelectPref">放送されるクール</label>
                        <!-- 放送されるクールの選択肢 -->
                        <select class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref" name="anime_cool">
                            <option selected>指定なし</option>
                            <option value="2">春</option>
                            <option value="3">夏</option>
                            <option value="4">秋</option>
                            <option value="1">冬</option>
                        </select><br>
  
                        <div class="custom-control custom-checkbox my-1 mr-sm-2">
                            <input type="checkbox" class="custom-control-input" id="customControlInline">
                            <label class="custom-control-label" for="customControlInline">Remember filter setting</label>
                        </div>
                        
                        <%= submit_tag '検索', class: 'btn btn-primary btn-lg' %>
                    <% end %>
                    <!-- ... フィルター部分のコード ... -->
                </div>
                
        </div>
    </div>

    <!-- 一覧表示 -->
    <div class="centered">
        <div class="text-center">アニメ検索 
            <div class="card p-5 w-100">
                <!-- カードの内容 -->
                <% if defined?(@result) && @result.present? %>
                    <% @result.each do |item| %>
                        <div class="card-body">
                            <!-- puts "最初のidは#{result[i]['id']}\n" --> 
                            <p>ID: <%= item['id'] %></p>
                            <p>Title: <%= item['title'] %></p>
                            <p><a href="<%= shangri_la_info_path %>?item=<%= item.to_json %>" class="btn btn-primary">詳細ページへ</a></p>
                            <hr>
                        </div>
                    <% end %>
                <% elsif defined?(@result) && @result.empty? %>
                    <p>No results found.</p>
                <% end %>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

app/views/shangri_la/info_page.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>インフォメーションページ</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- その他のヘッダー要素（必要に応じて） -->
</head> 
<body class="p-5">
	<div class="row d-flex justify-content-center">
	    <div class="card p-5 w-50">
		<h1><%= @info["title"] %></h1>
	    <a class="btn btn-primary mt-3 mb-5" href="<%= @info["public_url"] %>" target="_blank">公式サイトはこちら</a>
		<a class="twitter-timeline" href="https://twitter.com/<%= @info["twitter_account"] %>?ref_src=twsrc%5Etfw">Tweets by <%= @info["twitter_account"] %></a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
	</div>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

app/views/shangri_la/likes.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>お気に入りページ</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- その他のヘッダー要素（必要に応じて） -->
</head>
<body>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card mt-5">
          <div class="card-header">
            お気に入り
          </div>
          <div class="card-body">
            <%= form_tag '/shangri_la/login', method: :post, class: 'form-group', data: { turbo: false } do %>
              <div class="mb-3">
                <%= label_tag :email, 'メールアドレス', class: 'form-label' %>
                <%= text_field_tag :email, nil, class: 'form-control' %>
              </div>
              <div class="mb-3">
                <%= label_tag :pass, 'パスワード', class: 'form-label' %>
                <%= password_field_tag :pass, nil, class: 'form-control' %>
              </div>
              <div class="d-grid gap-2">
                <%= submit_tag 'ログイン', class: 'btn btn-primary btn-lg' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <p class="text-center mt-3"><%= link_to '戻る', root_path, class: 'btn btn-secondary' %></p>
  <p class="text-center"><%= link_to 'サインアップはこちら', new_user_path, class: 'btn btn-link' %></p>
  <!-- その他のHTMLコンテンツ（必要に応じて） -->
</body>
</html>

app/views/shangri_la/login_form.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ログインページ</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- その他のヘッダー要素（必要に応じて） -->
</head>
<body>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card mt-5">
          <div class="card-header">
            ログイン
          </div>
          <div class="card-body">
            <%= form_tag '/shangri_la/login', method: :post, class: 'form-group', data: { turbo: false } do %>
              <div class="mb-3">
                <%= label_tag :email, 'メールアドレス', class: 'form-label' %>
                <%= text_field_tag :email, nil, class: 'form-control' %>
              </div>
              <div class="mb-3">
                <%= label_tag :pass, 'パスワード', class: 'form-label' %>
                <%= password_field_tag :pass, nil, class: 'form-control' %>
              </div>
              <div class="d-grid gap-2">
                <%= submit_tag 'ログイン', class: 'btn btn-primary btn-lg' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <p class="text-center mt-3"><%= link_to '戻る', root_path, class: 'btn btn-secondary' %></p>
  <p class="text-center"><%= link_to 'サインアップはこちら', new_user_path, class: 'btn btn-link' %></p>
  <!-- その他のHTMLコンテンツ（必要に応じて） -->
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>新規登録ページ</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- その他のヘッダー要素（必要に応じて） -->
</head>
<body>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card mt-5">
          <div class="card-header">
            新規登録
          </div>
          <div class="card-body">
            <%= form_tag({ action: :create }, class: 'form-group') do %>
              <div class="mb-3">
                <%= label_tag :email, 'メールアドレス', class: 'form-label' %>
                <%= text_field_tag :email, nil, class: 'form-control' %>
              </div>
              <div class="mb-3">
                <%= label_tag :password, 'パスワード', class: 'form-label' %>
                <%= password_field_tag :password, nil, class: 'form-control' %>
              </div>
              <div class="mb-3">
                <%= label_tag :password_confirmation, 'パスワード(確認)', class: 'form-label' %>
                <%= password_field_tag :password_confirmation, nil, class: 'form-control' %>
              </div>
              <div class="d-grid gap-2">
                <%= submit_tag '新規登録', class: 'btn btn-primary btn-lg' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <h2 class="mt-5 text-center">ユーザー一覧</h2>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>ユーザー名</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.email %></td>
              <td>
                <%= link_to '削除', "/users/#{user.id}", method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: '本当に削除しますか？' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <p class="text-center mt-3"><%= link_to '戻る', shangri_la_login_form_path, class: 'btn btn-secondary' %></p>
  </div>
</body>
</html>